arch:
  - amd64
  - ppc64le
language: python

python:
  - 3.6

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=pypy
  - TOX_ENV=pypy3
  - TOX_ENV=flake8

install:
  - pip install "tox>=2.3.1" "coveralls>=1.1"

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
